Update styling of examples
IBM-Design/charts pull request #29
Opened 2017-01-25 03:19 UTC by matthewgallo

Closes #27 

#### Changelog

**New**

- Updated scatterplot example tab styling to be more consistent and aligned with the IBM Design Language (and accessible).

2017-01-25 03:33 UTC, seejamescode requested changes

2017-01-25 03:33 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
I would really love to see [this css-only way](https://codepen.io/rm/pen/ldhon) implemented before merging!

2017-01-25 03:50 UTC, matthewgallo commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Ok, will work on changing this!

2017-01-25 15:48 UTC, joshblack commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Is that example accessible @seejamescode?

2017-01-25 15:49 UTC, joshblack commented on examples/css/style.css
>  .scatterplot .menuEl, .scatterplot .menuEl2 {
Is there a convention for things that are `kebab-cased` and `camelCased`? noticed some of the selectors follow the former, some the latter.

2017-01-25 15:52 UTC, matthewgallo commented on examples/css/style.css
>  .scatterplot .menuEl, .scatterplot .menuEl2 {
In the original code from Accurat, the menu elements contained the class `menuEl` and `menuEl2`. We can change it to stay consistent with `kebab-cased` if that makes sense.

2017-01-25 16:01 UTC, joshblack commented on examples/css/style.css
>  .scatterplot .menuEl, .scatterplot .menuEl2 {
Up to you! Just was curious.

2017-01-26 14:05 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Only thing I see lacking for it to be accessible is when:
`.two:hover ~ hr {`

should also include `focus` along with `hover`.

2017-01-26 15:11 UTC, joshblack commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
I meant more like, `role="tablist"`, `role="tab"`, `aria-labbeledby`, `aria-controlled`, `aria-selected`, etc

2017-01-26 16:14 UTC, matthewgallo commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
I've updated it to this way, however, upon hovering the third tab the line starts from the first tab and then moves to the third tab. Whereas, in the js implementation the line starts from whatever tab you first hover on.
![scatterplot_tabs_animation](https://cloud.githubusercontent.com/assets/10215203/22339610/332aafe4-e3b0-11e6-8d9d-73b1b3fc7b81.gif)

2017-01-27 15:12 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Sorry for sending you a bad example. However, now you know how to do the hover transition with only css. So try keep using css for those transitions, but just trigger the transitions from the tablist classname during tab onClicks.

Also, Josh is right about those labels.

2017-01-27 15:12 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Sorry for sending you a bad example. However, now you know how to do the hover transition with only css. So try keep using css for those transitions, but just trigger the transitions from the tablist classname during tab onClicks.

Also, Josh is right about those labels.

2017-01-27 15:12 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Sorry for sending you a bad example. However, now you know how to do the hover transition with only css. So try keep using css for those transitions, but just trigger the transitions from the tablist classname during tab onClicks.

Also, Josh is right about those labels.

2017-01-27 15:12 UTC, seejamescode commented on examples/js/scatterplot.js
> +  var scatterplot1Tab1 = document.querySelector('.scatterplot-1-tab-1');
Sorry for sending you a bad example. However, now you know how to do the hover transition with only css. So try keep using css for those transitions, but just trigger the transitions from the tablist classname during tab onClicks.

Also, Josh is right about those labels.

2017-01-30 17:39 UTC, joshblack commented
What's the status of this PR?

2017-01-30 19:27 UTC, matthewgallo commented
I'm going to work on it this afternoon and fix everything specified above.

2017-02-02 15:05 UTC, seejamescode commented
Hey @matthewgallo, did you get those changes done for the tabs?

2017-02-02 15:12 UTC, matthewgallo commented
Yes, I did...however changing the tabs to radio buttons (like the example we had looked at before) stopped the d3 code from changing the active class on each tab. Besides that, this new solution seems best, all css.

2017-02-06 16:21 UTC, closed without merging