First draft of the bar charts
IBM-Design/charts pull request #51
Opened 2017-03-14 09:32 UTC by rodet

This PR introduces a first very rough draft that shows C3 bar graphs styled after our design. It misses a proper build yet though, as well as tests and linters. This could be used as a basis for a chart boilerplate to be used by all chart styles.

#### Changelog

**New**
- License and readme created
- First code from the draft we had
- Linters are disabled for now, that will need to be fixed later

2017-03-19 17:13 UTC, seejamescode commented on packages/charts-bar/package.json
> +  "author": "Abby Starnes & Stephane Rodet",
This can be an array! https://docs.npmjs.com/files/package.json#people-fields-author-contributors

2017-03-19 17:14 UTC, seejamescode commented on packages/charts-bar/src/charts-bar.scss
> +  @import "https://raw.githubusercontent.com/IBM-Design/colors/master/_ibm-colors.scss";
Before v1.0.0, we should reference the colors package in this project. We should add it as a peer dependency.

2017-03-19 17:16 UTC, seejamescode requested changes
Only thing I ask to change now is that the branch is `bar`. This is a great start!

2017-03-20 15:06 UTC, rodet commented on packages/charts-bar/package.json
> +  "author": "Abby Starnes & Stephane Rodet",
Indeed, only contributors can be an array though. I'll think about that and what makes most sense, and also look on the other projects.

2017-03-20 15:07 UTC, rodet commented on packages/charts-bar/src/charts-bar.scss
> +  @import "https://raw.githubusercontent.com/IBM-Design/colors/master/_ibm-colors.scss";
Definitely... This comes directly from GitHub but I understand we should change this very soon.

2017-03-20 15:10 UTC, closed without merging

2017-03-20 15:26 UTC, rodet commented
Closed in favour of #53 as I had a to create a new branch as requested.