Line Legend
IBM-Design/charts pull request #58
Opened 2017-03-27 15:46 UTC by sabov

### Related to #52 

- highlight related line on hover
- hide/show line on click

![animation](https://cloud.githubusercontent.com/assets/1277720/24365028/dfd7c036-1314-11e7-88f8-f79eee7db77e.gif)

If users want to hide legend:
```
ibmChart({
  data: {
    columns: [
      ['data1', 200, 300, 150, 400, 275, 360],
      ['data2', 210, 170, 240, 120, 160, 130],
      ['data3', 370, 350, 375, 340, 350, 340],
    ],
  },
  id: 'myChart',
  legend: { show: false },
});
```

2017-03-27 15:56 UTC, seejamescode requested changes
Great stuff! Some things missing:

- Responsiveness is lost
- The interactive legend needs to have html buttons for keyboard accessibility
- When the chart has a width of 1000px, the legend should have a width of 200px (according to the layout ai file). I only saw 75.55px

2017-03-28 09:34 UTC, winslet approved these changes
Looks great, happy with this, thanks for the GIF - really helpful when reviewing!

2017-04-03 21:55 UTC, seejamescode commented
Hey @sabov, the legend now collapses at the width it is supposed to. I do not know how to rerender the chart for the appropriate width though!

2017-04-10 14:54 UTC, seejamescode approved these changes

2017-04-10 14:54 UTC, merged